# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "FxGen Studio"
description: "FxGen Studio is a small independent game studio founded by one guy and decided to make their own."
author:      "Johann Nadalutti"
